### ISSUE TITLE
Error -- json: cannot unmarshal number into Go struct field BlockDevice.physicalblockdevice_set.used_size of type int

### ISSUE THREAD

**Issue by ednxzu** [maas/terraform-provider-maas#116] opened 2023-11-15 17:34 UTC
Basically what the title says, when provisioning a `maas_machine` resource, terraform throws an error related to the disk size 

provider version: `1.3.0` or `1.3.1`, both have the same behaviour

```
resource "maas_machine" "os_control_01" {
  hostname         = "os-control-01"
  domain           = "<redacted>"
  pool             = "openstack"
  power_parameters = {}
  power_type       = "manual"
  pxe_mac_address  = "<redacted>"
  zone             = "openstack"
}
```

throws 

```
│ Error: json: cannot unmarshal number 128032178176 into Go struct field BlockDevice.physicalblockdevice_set.used_size of type int
```

I'm not sure what additional info you might want, just tell me and I'll paste it here !

Cheers !

**Comment by troyanov** [comment] 2023-11-16 12:06
Hi @ednxzu 

May I ask you for the output of `uname -m` on the machine where you run Terraform provider?

**Comment by ednxzu** [comment] 2023-11-17 10:38
> Hi @ednxzu
> 
> May I ask you for the output of `uname -m` on the machine where you run Terraform provider?

Hey sorry I haven't got back to you, seems that you figured it out, thanks !

**Comment by troyanov** [comment] 2023-11-17 12:03
> Hey sorry I haven't got back to you, seems that you figured it out, thanks !

No worries. Hopefully the issue is fixed now.
It will take us some time to release a new version, but if you can try with the latest master, that would be great!

**Comment by troyanov** [comment] 2023-11-17 12:46
Ooops, this is still valid, until we update go.mod to point to the latest gomaasclient that includes https://github.com/maas/gomaasclient/pull/21 fix

**Comment by ednxzu** [comment] 2023-11-17 12:50
Hey, no worries ! Tho I noticed that this should be happening on 32 bits systems ? I ran into this error on my x86_64 workstation. 

For more context, With opentofu it throws this error, but terraform (the real one) doesn't. So I just reverted to using terraform for this. 

Maybe this is also a bug in tofu ?

**Comment by skatsaounis** [comment] 2023-11-22 07:58
Hi @ednxzu, with the merge of #121 we expect that your issue is no longer present in the provider binary created by the latest master branch. Since we are not ready yet to issue a new release, if you would like to try from now, you can build the provider locally and confirm that the error is gone. I am closing the issue for now and if we are still missing any bit we will reopen accordingly. Thank you for your engagement so far :beers:

**Closed by skatsaounis** 2023-11-22 07:58 UTC
Labels: bug
